routingRules:
  - domain: "nfh.global/testnet-evcharging"  # Retail domain
    version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_status
      - on_cancel
      - on_update
      - on_select
      - on_init
      - on_confirm
      - on_track
      - on_rate
      - on_support
      - on_discover

  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://fabric.nfh.global/beckn/catalog"
    endpoints:
      - publish
