appName: "onix-local"
log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transactionId
    - messageId
    - subscriber_id
    - module_id
http:
  port: 8082
  timeout:
    read: 30
    write: 30
    idle: 30
pluginManager:
  root: ./plugins
modules:
  - name: bppTxnReceiver
    path: /bpp/receiver/
    handler:
      type: std
      role: bpp
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: bpp.example.com
            keyId: 76EU7ofwRCF1aobQkShARrf1PAUsNpHqWUJoynPu9w45YFKmzqaPmy
            signingPrivateKey: 393fVJJsfqssJCRAjedKR2cKAjSLrjU3t+bICQ5KzYM=
            signingPublicKey: CqVy97DW45bcZPPrWIYGe2ldl9C93NFeVciiAEYsvR0=
            encrPrivateKey: 393fVJJsfqssJCRAjedKR2cKAjSLrjU3t+bICQ5KzYM=
            encrPublicKey: CqVy97DW45bcZPPrWIYGe2ldl9C93NFeVciiAEYsvR0=
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/tags/core-2.0.0-rc-eos-release/api/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "true"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io"
        cache:
          id: cache
          config:
            addr: redis:6379
        signValidator:
          id: signvalidator
        router:
          id: router
          config:
            routingConfig: ./config/local-beckn-one-routing-BPPReceiver.yaml
        payloadTransformer:
          id: reqmapper
          config:
            role: bpp
            mappingsFile: /app/config/mappings.yaml
        middleware:
          - id: reqpreprocessor
            config:
              contextKeys: transactionId,messageId
              role: bpp
      steps:
        - validateSign
        - addRoute
        - validateSchema
        - transformPayload

  - name: bppTxnCaller
    path: /bpp/caller/
    handler:
      type: std
      role: bpp
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: bpp.example.com
            keyId: 76EU7ofwRCF1aobQkShARrf1PAUsNpHqWUJoynPu9w45YFKmzqaPmy
            signingPrivateKey: 393fVJJsfqssJCRAjedKR2cKAjSLrjU3t+bICQ5KzYM=
            signingPublicKey: CqVy97DW45bcZPPrWIYGe2ldl9C93NFeVciiAEYsvR0=
            encrPrivateKey: 393fVJJsfqssJCRAjedKR2cKAjSLrjU3t+bICQ5KzYM=
            encrPublicKey: CqVy97DW45bcZPPrWIYGe2ldl9C93NFeVciiAEYsvR0=
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/tags/core-2.0.0-rc-eos-release/api/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "true"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io"
        cache:
          id: cache
          config:
            addr: redis:6379
        router:
          id: router
          config:
            routingConfig: ./config/local-beckn-one-routing-BPPCaller.yaml
        signer:
          id: signer
        payloadTransformer:
          id: reqmapper
          config:
            role: bpp
            mappingsFile: /app/config/mappings.yaml
        middleware:
          - id: reqpreprocessor
            config:
              contextKeys: transactionId,messageId
              role: bpp
      steps:
        - transformPayload
        - addRoute
        - sign
        - validateSchema
